apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dso-demo
      name: dso-demo
      annotations:
          seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/role: 'dso-demo'
          vault.hashicorp.com/agent-inject-secret-database: 'secret/dso-demo/database'
    spec:
      serviceAccountName: dso-demo
      automountServiceAccountToken: false
      containers:
      - image: crcedenp/dso-demo
        name: dso-demo
        ports:
        - containerPort: 8080
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 11000
        resources:
          requests:
              cpu: "50m"
              memory: "128Mi"
          limits:
              cpu: "250m"
              memory: "512Mi"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
status: {}
